//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.11 at 11:37:48 下午 CST 
//


package com.chinesejr.webservices.client.ValidateCodeWebService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cnValidateByteResult" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cnValidateByteResult"
})
@XmlRootElement(name = "cnValidateByteResponse")
public class CnValidateByteResponse {

    protected byte[] cnValidateByteResult;

    /**
     * Gets the value of the cnValidateByteResult property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCnValidateByteResult() {
        return cnValidateByteResult;
    }

    /**
     * Sets the value of the cnValidateByteResult property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCnValidateByteResult(byte[] value) {
        this.cnValidateByteResult = ((byte[]) value);
    }

}
