//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.11 at 11:37:48 下午 CST 
//


package com.chinesejr.webservices.client.ValidateCodeWebService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="byString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "byString"
})
@XmlRootElement(name = "enValidateByte")
public class EnValidateByte {

    protected String byString;

    /**
     * Gets the value of the byString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getByString() {
        return byString;
    }

    /**
     * Sets the value of the byString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setByString(String value) {
        this.byString = value;
    }

}
